import Img1 from "../../assets/b1.jpg";
import Img2 from "../../assets/b2.jpg";
import Img3 from "../../assets/b3.jpg";
import Img4 from "../../assets/b4.jpg";

const products = [
  {
    id: 1,
    name: " MacBook",
    description: "Apple",
    price: 19.99,
    image: [Img1, Img2, Img3, Img4],
    rating: 3.5,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 2,
    name: " MacBook 2",
    description: "Apple",
    price: 29.99,
    image: [Img2, Img3, Img4, Img1],
    rating: 5,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 3,
    name: " S22 Ultra",
    description: "Samaung",
    price: 19.99,
    image: [Img3, Img4, Img1, Img2],
    rating: 4.5,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 4,
    name: " S23 Ultra",
    description: "Samaung",
    price: 29.99,
    image: [Img4, Img1, Img2, Img3],
    rating: 4,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 5,
    name: " Iphone 15 Pro",
    description: "Apple",
    price: 19.99,
    image: [Img1, Img4, Img2, Img3],
    rating: 5,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 6,
    name: " S22 Ultra",
    description: "Samaung",
    price: 29.99,
    image: [Img2, Img3, Img1, Img4],
    rating: 3,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 7,
    name: "Iphone 14 Pro",
    description: "Apple",
    price: 19.99,
    image: [Img3,  Img1, Img2, Img4],
    rating: 3.75,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 8,
    name: "Iphone 15",
    description: "Apple",
    price: 29.99,
    image: [Img4,  Img1, Img3, Img2],
    rating: 4.25,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 9,
    name: "Iphone 13",
    description: "Apple",
    price: 19.99,
    image: [Img2,  Img4, Img1, Img3],
    rating: 3,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 10,
    name: "OnePlus 12",
    description: "Vivo",
    price: 29.99,
    image: [Img3, Img1, Img2, Img4],
    rating: 4.85,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 11,
    name: "Iqoo 12 ",
    description: "Vivo",
    price: 29.99,
    image: [Img3, Img2, Img1, Img4],
    rating: 3.15,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
  {
    id: 12,
    name: "Honor Mate 20",
    description: "Hauwai",
    price: 29.99,
    image: [Img1, Img4, Img3, Img2],
    rating: 5,
    reviews: [
      { name:'A',comment: "Great product!" },
      { name:'B',comment: "Amazing quality." },
      { name:'C',comment: "Great product!" },
      { name:'D',comment: "Amazing quality." },
      { name:'E',comment: "Great product!" },
      { name:'F',comment: "Amazing quality." },
      { name:'G',comment: "Great product!" },
      { name:'H',comment: "Amazing quality." },
    ],
  },
];

export default products;
